### ISSUE TITLE
16kW Sunsynk has 3 x MPPT's and how can we add in Micro Inverter

### ISSUE THREAD

**Issue by starrateit** [slipx06/sunsynk-power-flow-card#17] opened 2023-05-08 19:49 UTC
Hi,

Any chance we could get an updated card which includes 3 x MPPT's?
Then can we use the Aux for power coming in from a Micro Inverter?

Thanks
Spencer

**Comment by slipx06** [comment] 2023-05-08 21:54
Hi. This will require some work to move svg elements around to make space. If there's enough demand for this it can be done.

**Comment by starrateit** [comment] 2023-05-09 05:17
Thank you, the same issue will exist with the larger 3 phase units they have 4 MPPT’s. So ideally design to encompass all versions, the inclusion of all 4 will be best and use case will increase!

Thanks,
Spencer

**Comment by slipx06** [comment] 2023-05-09 12:01
I have an idea on how we can add up to 4. :)

**Comment by slipx06** [comment] 2023-05-09 13:09
Can you reattach the image

**Comment by starrateit** [comment] 2023-05-09 13:11
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by starrateit** [comment] 2023-05-09 13:35
![WhatsApp Image 2023-05-09 at 15 35 14](https://github.com/slipx06/sunsynk-power-flow-card/assets/35799387/919a1f57-0d14-44f0-9890-baeed24964c2)

**Comment by starrateit** [comment] 2023-05-09 13:35
Sorry there we go

**Comment by slipx06** [comment] 2023-05-09 13:38
Ok so that is 307 Watt input on the aux port. I'll check the logic. Dot should be moving from right to left

**Comment by starrateit** [comment] 2023-05-09 13:42
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/35799387/16290cbf-f730-4e2e-9a69-65f7db8b7073)

So the total for example should be this. if you want to do the maths and check everything

**Comment by starrateit** [comment] 2023-05-09 13:46
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/35799387/d253e172-f940-469d-82bc-66543995603e)

Here are the directions... 
I think Aux should be the other way based on the way the PV DC Solar is flowing

**Comment by starrateit** [comment] 2023-05-09 13:47
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/35799387/fdfe7cc2-a4a3-454b-af91-1f5fa574f831)

This gives you all the PV info including the Aux in the Entity tile on the bottom right

**Comment by slipx06** [comment] 2023-05-09 14:01
The thing is you can use the aux port feed power to another load or receive as you have i.e generator or micro-invetrer.  I need to create a config option to cater for this. In the mean time  you can create a template sensor to assign a negative value to input power to correct the flow. 

`sensor:
  - platform: template
    sensors:
      aux_inverted:
	friendly_name: "Aux Input Power Inverted"
        value_template: "{{ -1 * states('sensor.ss_aux_power') | float }}"
        unit_of_measurement: 'W' `

Thanks for the valuable feedback

**Comment by starrateit** [comment] 2023-05-09 14:04
Ok cool yeah that was what I was thinking, will do. I can also try and work around the MPPT’s for now by grouping. Not ideal as I can’t then see a problematic MPPT but will use it is a temp fix which should work.
Thanks for the help and your cool card. 😊

**Comment by slipx06** [comment] 2023-05-09 18:45
Something like this 


![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/c93443d1-4aed-4ab8-91ea-d0b47ec01725)

**Comment by starrateit** [comment] 2023-05-10 05:12
😀 yes that looks great 👍🏻👍🏻

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by slipx06** [comment] 2023-05-10 07:28
I've just pushed a new release. v1.3.0 with this. There is also the option to invert AUX

**Comment by starrateit** [comment] 2023-05-10 09:38
Excellent I will give it a try!

**Comment by starrateit** [comment] 2023-05-10 10:08
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/35799387/e68acaaf-15e8-493d-ad99-ca9c122ab7e0)

Looking good, thanks for adding the option to remove the Non-essentials! 
Just a small bug seems to have come in where the flow direction has stopped working on the Grid and on the Aux. Or do I need to reload?

**Comment by slipx06** [comment] 2023-05-10 10:28
I'll fix that. I know what the issue is

**Comment by slipx06** [comment] 2023-05-10 11:57
Just pushed and update. Should be fixed in v1.3.2. Note that the AUX value of the card will not show a negative number. The flow animation is used to indicate input or output. You just have to make sure that your sensor records a negative number for input and positive for output

**Comment by starrateit** [comment] 2023-05-10 14:40
Cool thanks.

**Comment by starrateit** [comment] 2023-05-10 14:41
Ok will do a template for it and let you know all is sorted.

**Closed** 2023-05-17 09:44 UTC
